### ISSUE TITLE
The Folder "ImageData" is missing

### ISSUE THREAD

**Issue by dlnn** [DKorablin/ApkReader#2]
<Compile Include="..\..\ImageData\IBaseRow.cs">
      <Link>Data\Interface\IBaseRow.cs</Link>
    </Compile>
    <Compile Include="..\..\ImageData\ICell.cs">
      <Link>Data\Interface\ICell.cs</Link>
    </Compile>
    <Compile Include="..\..\ImageData\IColumn.cs">
      <Link>Data\Interface\IColumn.cs</Link>
    </Compile>
    <Compile Include="..\..\ImageData\IRow.cs">
      <Link>Data\Interface\IRow.cs</Link>
    </Compile>
    <Compile Include="..\..\ImageData\IRowPointer.cs">
      <Link>Data\Interface\IRowPointer.cs</Link>
    </Compile>
    <Compile Include="..\..\ImageData\ITable.cs">
      <Link>Data\Interface\ITable.cs</Link>
    </Compile>
    <Compile Include="..\..\ImageData\ITables.cs">
      <Link>Data\Interface\ITables.cs</Link>
    </Compile>

**Comment by DKorablin** [comment]
Thanks for notification. I've retarget shared files to submodule
